apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicloud-app
  namespace: multicloud-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multicloud-app
  template:
    metadata:
      labels:
        app: multicloud-app
    spec:
      containers:
        - name: multicloud-app
          image: docker-registry.docker-registry.svc.cluster.local:5000/multicloud-app:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: multicloud-app-service
  namespace: multicloud-devops
spec:
  selector:
    app: multicloud-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
# Deployed via ARC CI pipeline
# retrigger 1790087702
# retrigger 1790089362
# retrigger 1790090215 after tcp_mtu_probing fix
