---

- name: Install Git
  apt:
    name: git
    state: present
  become: true

- name: Set Git user name
  git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"
  

- name: Set Git user email
  git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"
  